const datas = [
    { word: "achieve", meaning: "mencapai tujuan" },
    { word: "adapt", meaning: "menyesuaikan diri" },
    { word: "analyze", meaning: "menganalisis data" },
    { word: "approach", meaning: "pendekatan, cara" },
    { word: "arrange", meaning: "mengatur, menyusun" },
    { word: "assist", meaning: "membantu, menolong" },
    { word: "assume", meaning: "menganggap, menduga" },
    { word: "attempt", meaning: "mencoba, upaya" },
    { word: "balance", meaning: "keseimbangan" },
    { word: "benefit", meaning: "manfaat, keuntungan" },
    { word: "challenge", meaning: "tantangan" },
    { word: "combine", meaning: "menggabungkan" },
    { word: "communicate", meaning: "berkomunikasi" },
    { word: "compare", meaning: "membandingkan" },
    { word: "complain", meaning: "mengeluh" },
    { word: "conclude", meaning: "menyimpulkan" },
    { word: "confirm", meaning: "mengkonfirmasi" },
    { word: "consider", meaning: "mempertimbangkan" },
    { word: "contribute", meaning: "berkontribusi" },
    { word: "convince", meaning: "meyakinkan" },
    { word: "create", meaning: "membuat, menciptakan" },
    { word: "criticize", meaning: "mengkritik" },
    { word: "debate", meaning: "debat, membahas" },
    { word: "define", meaning: "mendefinisikan" },
    { word: "demonstrate", meaning: "menunjukkan, demo" },
    { word: "describe", meaning: "menggambarkan" },
    { word: "develop", meaning: "mengembangkan" },
    { word: "discuss", meaning: "membahas" },
    { word: "display", meaning: "menampilkan" },
    { word: "distinguish", meaning: "membedakan" },
    { word: "emphasize", meaning: "menekankan" },
    { word: "encourage", meaning: "mendorong, menyemangati" },
    { word: "enhance", meaning: "meningkatkan" },
    { word: "establish", meaning: "membangun, mendirikan" },
    { word: "evaluate", meaning: "mengevaluasi" },
    { word: "examine", meaning: "memeriksa" },
    { word: "explore", meaning: "menjelajahi" },
    { word: "express", meaning: "mengungkapkan" },
    { word: "identify", meaning: "mengidentifikasi" },
    { word: "illustrate", meaning: "menggambarkan, ilustrasi" },
    { word: "improve", meaning: "memperbaiki" },
    { word: "indicate", meaning: "menunjukkan" },
    { word: "influence", meaning: "mempengaruhi" },
    { word: "inform", meaning: "memberi tahu" },
    { word: "inspire", meaning: "menginspirasi" },
    { word: "interpret", meaning: "menafsirkan" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "maintain", meaning: "memelihara" },
    { word: "manage", meaning: "mengelola" },
    { word: "mention", meaning: "menyebutkan" },
    { word: "observe", meaning: "mengamati" },
    { word: "participate", meaning: "berpartisipasi" },
    { word: "perceive", meaning: "merasakan, menganggap" },
    { word: "persuade", meaning: "membujuk" },
    { word: "predict", meaning: "memprediksi" },
    { word: "prefer", meaning: "lebih suka" },
    { word: "prevent", meaning: "mencegah" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "produce", meaning: "menghasilkan, produksi" },
    { word: "promote", meaning: "mempromosikan" },
    { word: "propose", meaning: "mengusulkan" },
    { word: "react", meaning: "bereaksi" },
    { word: "recommend", meaning: "merekomendasikan" },
    { word: "reduce", meaning: "mengurangi" },
    { word: "reflect", meaning: "mencerminkan" },
    { word: "refuse", meaning: "menolak" },
    { word: "relate", meaning: "menghubungkan" },
    { word: "rely", meaning: "mengandalkan" },
    { word: "replace", meaning: "mengganti" },
    { word: "require", meaning: "membutuhkan" },
    { word: "respond", meaning: "menanggapi" },
    { word: "restrict", meaning: "membatasi" },
    { word: "retain", meaning: "mempertahankan" },
    { word: "reveal", meaning: "mengungkapkan" },
    { word: "select", meaning: "memilih" },
    { word: "solve", meaning: "memecahkan" },
    { word: "specify", meaning: "menentukan" },
    { word: "suggest", meaning: "menyarankan" },
    { word: "support", meaning: "mendukung" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "sustain", meaning: "mempertahankan" },
    { word: "tend", meaning: "cenderung" },
    { word: "threaten", meaning: "mengancam" },
    { word: "transfer", meaning: "memindahkan" },
    { word: "transform", meaning: "mengubah bentuk" },
    { word: "undergo", meaning: "menjalani, mengalami" },
    { word: "undertake", meaning: "melakukan, mengerjakan" },
    { word: "vary", meaning: "bervariasi, beragam" },
    { word: "verify", meaning: "memverifikasi" },
    { word: "witness", meaning: "menyaksikan, saksi" },
    { word: "accurate", meaning: "akurat, tepat" },
    { word: "adequate", meaning: "memadai, cukup" },
    { word: "apparent", meaning: "jelas, tampak" },
    { word: "complex", meaning: "kompleks, rumit" },
    { word: "consistent", meaning: "konsisten, sesuai" },
    { word: "crucial", meaning: "penting, krusial" },
    { word: "distinct", meaning: "berbeda, jelas" },
    { word: "efficient", meaning: "efisien" },
    { word: "frequent", meaning: "sering" },
    { word: "relevant", meaning: "relevan, sesuai" },
    { word: "abandon", meaning: "meninggalkan" },
    { word: "absorb", meaning: "menyerap" },
    { word: "abstract", meaning: "abstrak" },
    { word: "abundant", meaning: "melimpah" },
    { word: "access", meaning: "akses" },
    { word: "acquire", meaning: "memperoleh" },
    { word: "adapt", meaning: "menyesuaikan" },
    { word: "adjust", meaning: "menyesuaikan" },
    { word: "advocate", meaning: "menganjurkan" },
    { word: "allocate", meaning: "mengalokasikan" },
    { word: "ambiguous", meaning: "ambigu, ganda" },
    { word: "amend", meaning: "mengubah, memperbaiki" },
    { word: "anticipate", meaning: "mengantisipasi" },
    { word: "apparent", meaning: "jelas, nyata" },
    { word: "append", meaning: "melampirkan, menambahkan" },
    { word: "appreciate", meaning: "menghargai" },
    { word: "arbitrary", meaning: "sewenang-wenang" },
    { word: "assemble", meaning: "merakit, mengumpulkan" },
    { word: "assure", meaning: "memastikan, menjamin" },
    { word: "attach", meaning: "melampirkan" },
    { word: "attain", meaning: "mencapai" },
    { word: "attribute", meaning: "menganggap, ciri" },
    { word: "author", meaning: "penulis" },
    { word: "automate", meaning: "mengotomatiskan" },
    { word: "aware", meaning: "sadar, tahu" },
    { word: "bias", meaning: "bias, prasangka" },
    { word: "brief", meaning: "singkat" },
    { word: "capable", meaning: "mampu" },
    { word: "cease", meaning: "berhenti" },
    { word: "clarify", meaning: "memperjelas" },
    { word: "coherent", meaning: "koheren, masuk akal" },
    { word: "coincide", meaning: "bersamaan" },
    { word: "collapse", meaning: "runtuh" },
    { word: "commence", meaning: "memulai" },
    { word: "compatible", meaning: "kompatibel" },
    { word: "compile", meaning: "mengkompilasi" },
    { word: "conceive", meaning: "membayangkan, memahami" },
    { word: "concentrate", meaning: "berkonsentrasi" },
    { word: "concurrent", meaning: "bersamaan" },
    { word: "confine", meaning: "membatasi" },
    { word: "conform", meaning: "menyesuaikan diri" },
    { word: "consent", meaning: "persetujuan" },
    { word: "constrain", meaning: "membatasi, menahan" },
    { word: "consult", meaning: "berkonsultasi" },
    { word: "consume", meaning: "mengonsumsi" },
    { word: "contradict", meaning: "bertentangan" },
    { word: "contrary", meaning: "bertentangan" },
    { word: "convert", meaning: "mengubah" },
    { word: "convince", meaning: "meyakinkan" },
    { word: "cooperate", meaning: "bekerja sama" },
    { word: "coordinate", meaning: "mengkoordinasikan" },
    { word: "core", meaning: "inti" },
    { word: "correspond", meaning: "sesuai, berkorespondensi" },
    { word: "criteria", meaning: "kriteria" },
    { word: "crucial", meaning: "krusial, penting" },
    { word: "currency", meaning: "mata uang" },
    { word: "deduce", meaning: "menyimpulkan" },
    { word: "definite", meaning: "pasti" },
    { word: "deny", meaning: "menyangkal" },
    { word: "depress", meaning: "menekan, membuat sedih" },
    { word: "derive", meaning: "berasal dari" },
    { word: "detect", meaning: "mendeteksi" },
    { word: "deviate", meaning: "menyimpang" },
    { word: "differentiate", meaning: "membedakan" },
    { word: "diminish", meaning: "mengurangi, mengecilkan" },
    { word: "discrete", meaning: "diskrit, terpisah" },
    { word: "displace", meaning: "menggantikan" },
    { word: "display", meaning: "menampilkan" },
    { word: "distribute", meaning: "mendistribusikan" },
    { word: "diverse", meaning: "beragam" },
    { word: "domain", meaning: "domain, ranah" },
    { word: "dominate", meaning: "mendominasi" },
    { word: "draft", meaning: "draf, rancangan" },
    { word: "duration", meaning: "durasi, jangka waktu" },
    { word: "eliminate", meaning: "menghilangkan" },
    { word: "emerge", meaning: "muncul" },
    { word: "empirical", meaning: "empiris" },
    { word: "enable", meaning: "memungkinkan" },
    { word: "enforce", meaning: "menegakkan" },
    { word: "enhance", meaning: "meningkatkan" },
    { word: "enormous", meaning: "besar sekali" },
    { word: "ensure", meaning: "memastikan" },
    { word: "entity", meaning: "entitas, keberadaan" },
    { word: "equip", meaning: "melengkapi" },
    { word: "equivalent", meaning: "setara, ekuivalen" },
    { word: "erode", meaning: "mengikis" },
    { word: "establish", meaning: "membangun" },
    { word: "evaluate", meaning: "mengevaluasi" },
    { word: "eventual", meaning: "akhirnya" },
    { word: "evident", meaning: "jelas, terbukti" },
    { word: "evolve", meaning: "berevolusi, berkembang" },
    { word: "exclude", meaning: "mengecualikan" },
    { word: "exhibit", meaning: "memamerkan" },
    { word: "expand", meaning: "memperluas" },
    { word: "expert", meaning: "ahli" },
    { word: "explicit", meaning: "eksplisit, jelas" },
    { word: "exploit", meaning: "memanfaatkan" },
    { word: "expose", meaning: "mengungkapkan, memaparkan" },
    { word: "external", meaning: "eksternal, luar" },
    { word: "facilitate", meaning: "memfasilitasi" },
    { word: "feature", meaning: "fitur, ciri" },
    { word: "federal", meaning: "federal" },
    { word: "finite", meaning: "terbatas" },
    { word: "flexible", meaning: "fleksibel, lentur" },
    { word: "fluctuate", meaning: "berfluktuasi" },
    { word: "focus", meaning: "fokus" },
    { word: "forthcoming", meaning: "mendatang" },
    { word: "foundation", meaning: "fondasi, dasar" },
    { word: "framework", meaning: "kerangka kerja" },
    { word: "function", meaning: "fungsi" },
    { word: "fund", meaning: "dana" },
    { word: "fundamental", meaning: "fundamental, dasar" },
    { word: "generate", meaning: "menghasilkan" },
    { word: "generation", meaning: "generasi" },
    { word: "grade", meaning: "tingkat, nilai" },
    { word: "grant", meaning: "memberikan, hibah" },
    { word: "guarantee", meaning: "menjamin" },
    { word: "highlight", meaning: "menyoroti" },
    { word: "hypothesis", meaning: "hipotesis" },
    { word: "identical", meaning: "identik" },
    { word: "ideology", meaning: "ideologi" },
    { word: "ignorant", meaning: "bodoh, tidak tahu" },
    { word: "illustrate", meaning: "mengilustrasikan" },
    { word: "immense", meaning: "sangat besar" },
    { word: "impact", meaning: "dampak" },
    { word: "implement", meaning: "mengimplementasikan" },
    { word: "implicate", meaning: "melibatkan, menyiratkan" },
    { word: "implicit", meaning: "tersirat" },
    { word: "impose", meaning: "memaksakan" },
    { word: "incentive", meaning: "insentif" },
    { word: "incidence", meaning: "insiden, kejadian" },
    { word: "incline", meaning: "cenderung" },
    { word: "incorporate", meaning: "menggabungkan" },
    { word: "indicate", meaning: "menunjukkan" },
    { word: "individual", meaning: "individu" },
    { word: "induce", meaning: "mendorong" },
    { word: "inevitable", meaning: "tak terhindarkan" },
    { word: "infer", meaning: "menyimpulkan" },
    { word: "inhibit", meaning: "menghambat" },
    { word: "initial", meaning: "awal" },
    { word: "initiate", meaning: "memulai" },
    { word: "innovate", meaning: "berinovasi" },
    { word: "input", meaning: "masukan" },
    { word: "insert", meaning: "memasukkan" },
    { word: "insight", meaning: "wawasan" },
    { word: "inspect", meaning: "memeriksa" },
    { word: "instance", meaning: "contoh, kasus" },
    { word: "institute", meaning: "lembaga, mendirikan" },
    { word: "integral", meaning: "integral, penting" },
    { word: "integrate", meaning: "mengintegrasikan" },
    { word: "integrity", meaning: "integritas" },
    { word: "intense", meaning: "intens, kuat" },
    { word: "interact", meaning: "berinteraksi" },
    { word: "intermediate", meaning: "menengah" },
    { word: "internal", meaning: "internal, dalam" },
    { word: "interpret", meaning: "menafsirkan" },
    { word: "interval", meaning: "interval, selang" },
    { word: "intervene", meaning: "campur tangan" },
    { word: "intrinsic", meaning: "intrinsik" },
    { word: "invest", meaning: "berinvestasi" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "invoke", meaning: "memohon, memanggil" },
    { word: "involve", meaning: "melibatkan" },
    { word: "isolate", meaning: "mengisolasi" },
    { word: "issue", meaning: "masalah, isu" },
    { word: "item", meaning: "item, barang" },
    { word: "job", meaning: "pekerjaan" },
    { word: "journal", meaning: "jurnal" },
    { word: "justify", meaning: "membenarkan" },
    { word: "label", meaning: "label" },
    { word: "lecture", meaning: "kuliah" },
    { word: "legal", meaning: "legal, hukum" },
    { word: "legislate", meaning: "membuat undang-undang" },
    { word: "levy", meaning: "membebankan pajak" },
    { word: "liberal", meaning: "liberal, bebas" },
    { word: "license", meaning: "lisensi" },
    { word: "likewise", meaning: "demikian juga" },
    { word: "link", meaning: "menghubungkan" },
    { word: "locate", meaning: "menemukan lokasi" },
    { word: "logic", meaning: "logika" },
    { word: "manual", meaning: "manual" },
    { word: "margin", meaning: "margin, batas" },
    { word: "mature", meaning: "dewasa" },
    { word: "mediate", meaning: "menengahi" },
    { word: "medium", meaning: "medium, sedang" },
    { word: "mental", meaning: "mental" },
    { word: "method", meaning: "metode" },
    { word: "migrate", meaning: "bermigrasi" },
    { word: "minimize", meaning: "meminimalkan" },
    { word: "minimum", meaning: "minimum" },
    { word: "ministry", meaning: "kementerian" },
    { word: "mode", meaning: "mode, cara" },
    { word: "modify", meaning: "memodifikasi" },
    { word: "monitor", meaning: "memantau" },
    { word: "motivate", meaning: "memotivasi" },
    { word: "mutual", meaning: "timbal balik" },
    { word: "negate", meaning: "meniadakan" },
    { word: "network", meaning: "jaringan" },
    { word: "neutral", meaning: "netral" },
    { word: "nevertheless", meaning: "namun demikian" },
    { word: "nonetheless", meaning: "meskipun demikian" },
    { word: "notion", meaning: "gagasan" },
    { word: "objective", meaning: "objektif, tujuan" },
    { word: "obtain", meaning: "memperoleh" },
    { word: "obvious", meaning: "jelas, nyata" },
    { word: "occupy", meaning: "menduduki" },
    { word: "occur", meaning: "terjadi" },
    { word: "odd", meaning: "aneh, ganjil" },
    { word: "offset", meaning: "mengimbangi" },
    { word: "ongoing", meaning: "berlangsung" },
    { word: "option", meaning: "opsi, pilihan" },
    { word: "orient", meaning: "mengorientasikan" },
    { word: "outcome", meaning: "hasil" },
    { word: "output", meaning: "output, keluaran" },
    { word: "overall", meaning: "keseluruhan" },
    { word: "overlap", meaning: "tumpang tindih" },
    { word: "panel", meaning: "panel" },
    { word: "paradigm", meaning: "paradigma" },
    { word: "paragraph", meaning: "paragraf" },
    { word: "parallel", meaning: "paralel" },
    { word: "parameter", meaning: "parameter" },
    { word: "participate", meaning: "berpartisipasi" },
    { word: "partner", meaning: "mitra" },
    { word: "perceive", meaning: "mempersepsikan" },
    { word: "percent", meaning: "persen" },
    { word: "period", meaning: "periode" },
    { word: "persist", meaning: "bertahan, tetap" },
    { word: "perspective", meaning: "perspektif" },
    { word: "phase", meaning: "fase" },
    { word: "phenomenon", meaning: "fenomena" },
    { word: "philosophy", meaning: "filsafat" },
    { word: "physical", meaning: "fisik" },
    { word: "plus", meaning: "plus, tambahan" },
    { word: "policy", meaning: "kebijakan" },
    { word: "portion", meaning: "bagian" },
    { word: "pose", meaning: "menimbulkan, berpose" },
    { word: "positive", meaning: "positif" },
    { word: "potential", meaning: "potensi" },
    { word: "precede", meaning: "mendahului" },
    { word: "precise", meaning: "tepat, presisi" },
    { word: "predict", meaning: "memprediksi" },
    { word: "predominant", meaning: "dominan" },
    { word: "presume", meaning: "menduga" },
    { word: "previous", meaning: "sebelumnya" },
    { word: "primary", meaning: "utama, primer" },
    { word: "prime", meaning: "utama, prima" },
    { word: "principal", meaning: "utama, kepala" },
    { word: "prior", meaning: "sebelumnya, prioritas" },
    { word: "priority", meaning: "prioritas" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "process", meaning: "proses" },
    { word: "professional", meaning: "profesional" },
    { word: "prohibit", meaning: "melarang" },
    { word: "project", meaning: "proyek, memproyeksikan" },
    { word: "promote", meaning: "mempromosikan" },
    { word: "proportion", meaning: "proporsi" },
    { word: "prospect", meaning: "prospek" },
    { word: "protocol", meaning: "protokol" },
    { word: "psychology", meaning: "psikologi" },
    { word: "publication", meaning: "publikasi" },
    { word: "publish", meaning: "menerbitkan" },
    { word: "purchase", meaning: "membeli" },
    { word: "pursue", meaning: "mengejar" },
    { word: "qualitative", meaning: "kualitatif" },
    { word: "quote", meaning: "mengutip" },
    { word: "radical", meaning: "radikal" },
    { word: "random", meaning: "acak" },
    { word: "range", meaning: "rentang" },
    { word: "ratio", meaning: "rasio" },
    { word: "rational", meaning: "rasional" },
    { word: "react", meaning: "bereaksi" },
    { word: "recover", meaning: "memulihkan" },
    { word: "refine", meaning: "memurnikan" },
    { word: "regime", meaning: "rezim" },
    { word: "region", meaning: "wilayah" },
    { word: "register", meaning: "mendaftar" },
    { word: "regulate", meaning: "mengatur" },
    { word: "reinforce", meaning: "memperkuat" },
    { word: "reject", meaning: "menolak" },
    { word: "relax", meaning: "bersantai" },
    { word: "release", meaning: "melepaskan" },
    { word: "relevant", meaning: "relevan" },
    { word: "rely", meaning: "mengandalkan" },
    { word: "remove", meaning: "menghapus" },
    { word: "render", meaning: "memberikan, membuat" },
    { word: "renew", meaning: "memperbarui" },
    { word: "require", meaning: "membutuhkan" },
    { word: "reside", meaning: "tinggal, berdiam" },
    { word: "resolve", meaning: "menyelesaikan" },
    { word: "resource", meaning: "sumber daya" },
    { word: "respond", meaning: "menanggapi" },
    { word: "restore", meaning: "memulihkan" },
    { word: "restrict", meaning: "membatasi" },
    { word: "retain", meaning: "mempertahankan" },
    { word: "reveal", meaning: "mengungkapkan" },
    { word: "reverse", meaning: "membalikkan" },
    { word: "revise", meaning: "merevisi" },
    { word: "revolution", meaning: "revolusi" },
    { word: "rigid", meaning: "kaku, teguh" },
    { word: "role", meaning: "peran" },
    { word: "route", meaning: "rute, jalur" },
    { word: "scenario", meaning: "skenario" },
    { word: "schedule", meaning: "jadwal" },
    { word: "scheme", meaning: "skema, rencana" },
    { word: "scope", meaning: "cakupan" },
    { word: "section", meaning: "bagian" },
    { word: "sector", meaning: "sektor" },
    { word: "secure", meaning: "mengamankan" },
    { word: "seek", meaning: "mencari" },
    { word: "select", meaning: "memilih" },
    { word: "sequence", meaning: "urutan" },
    { word: "series", meaning: "seri" },
    { word: "shift", meaning: "pergeseran" },
    { word: "significant", meaning: "signifikan, penting" },
    { word: "similar", meaning: "serupa" },
    { word: "simulate", meaning: "mensimulasikan" },
    { word: "site", meaning: "situs" },
    { word: "so-called", meaning: "yang disebut" },
    { word: "sole", meaning: "satu-satunya" },
    { word: "somewhat", meaning: "agak" },
    { word: "source", meaning: "sumber" },
    { word: "specify", meaning: "menentukan" },
    { word: "sphere", meaning: "lingkup, bola" },
    { word: "stable", meaning: "stabil" },
    { word: "statistic", meaning: "statistik" },
    { word: "status", meaning: "status" },
    { word: "straightforward", meaning: "lurus ke depan" },
    { word: "strategy", meaning: "strategi" },
    { word: "stress", meaning: "stres, tekanan" },
    { word: "structure", meaning: "struktur" },
    { word: "style", meaning: "gaya" },
    { word: "subordinate", meaning: "bawahan" },
    { word: "subsequent", meaning: "berikutnya" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "successor", meaning: "penerus" },
    { word: "sufficient", meaning: "cukup" },
    { word: "sum", meaning: "jumlah" },
    { word: "summary", meaning: "ringkasan" },
    { word: "supplement", meaning: "suplemen, tambahan" },
    { word: "survey", meaning: "survei" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "suspend", meaning: "menunda" },
    { word: "sustain", meaning: "mempertahankan" },
    { word: "symbol", meaning: "simbol" },
    { word: "tape", meaning: "pita" },
    { word: "target", meaning: "target" },
    { word: "task", meaning: "tugas" },
    { word: "team", meaning: "tim" },
    { word: "technique", meaning: "teknik" },
    { word: "technology", meaning: "teknologi" },
    { word: "temporary", meaning: "sementara" },
    { word: "tense", meaning: "tegang" },
    { word: "terminate", meaning: "mengakhiri" },
    { word: "theme", meaning: "tema" },
    { word: "theory", meaning: "teori" },
    { word: "thereby", meaning: "dengan demikian" },
    { word: "thesis", meaning: "tesis" },
    { word: "topic", meaning: "topik" },
    { word: "trace", meaning: "melacak" },
    { word: "tradition", meaning: "tradisi" },
    { word: "transfer", meaning: "mentransfer" },
    { word: "transform", meaning: "mengubah" },
    { word: "transmit", meaning: "mengirimkan" },
    { word: "transport", meaning: "mengangkut" },
    { word: "trend", meaning: "tren" },
    { word: "trigger", meaning: "memicu" },
    { word: "ultimate", meaning: "ultimate, terakhir" },
    { word: "undergo", meaning: "mengalami" },
    { word: "undertake", meaning: "melakukan" },
    { word: "uniform", meaning: "seragam" },
    { word: "unique", meaning: "unik" },
    { word: "utilize", meaning: "memanfaatkan" },
    { word: "valid", meaning: "sah" },
    { word: "vary", meaning: "bervariasi" },
    { word: "vehicle", meaning: "kendaraan" },
    { word: "via", meaning: "melalui" },
    { word: "virtual", meaning: "virtual" },
    { word: "vision", meaning: "visi" },
    { word: "visual", meaning: "visual" },
    { word: "volume", meaning: "volume" },
    { word: "voluntary", meaning: "sukarela" },
    { word: "welfare", meaning: "kesejahteraan" },
    { word: "whereas", meaning: "sedangkan" },
    { word: "widespread", meaning: "luas, menyebar" },
    { word: "willing", meaning: "bersedia" },
    { word: "witness", meaning: "menyaksikan" },
    { word: "withdraw", meaning: "menarik diri" },
    { word: "yield", meaning: "menghasilkan, menyerah" },
    { word: "zone", meaning: "zona, area" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "foundation", meaning: "fondasi" },
    { word: "initial", meaning: "awal" },
    { word: "interval", meaning: "interval" },
    { word: "restrict", meaning: "membatasi" },
    { word: "aware", meaning: "sadar" },
    { word: "attempt", meaning: "upaya" },
    { word: "strategy", meaning: "strategi" },
    { word: "expert", meaning: "ahli" },
    { word: "evident", meaning: "jelas" },
    { word: "draft", meaning: "draf" },
    { word: "uniform", meaning: "seragam" },
    { word: "criteria", meaning: "kriteria" },
    { word: "proportion", meaning: "proporsi" },
    { word: "transform", meaning: "mengubah" },
    { word: "supplement", meaning: "suplemen" },
    { word: "parameter", meaning: "parameter" },
    { word: "prospect", meaning: "prospek" },
    { word: "restrict", meaning: "membatasi" },
    { word: "task", meaning: "tugas" },
    { word: "automate", meaning: "mengotomatiskan" },
    { word: "prevent", meaning: "mencegah" },
    { word: "supplement", meaning: "suplemen" },
    { word: "psychology", meaning: "psikologi" },
    { word: "allocate", meaning: "mengalokasikan" },
    { word: "eliminate", meaning: "menghilangkan" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "ideology", meaning: "ideologi" },
    { word: "offset", meaning: "mengimbangi" },
    { word: "compare", meaning: "membandingkan" },
    { word: "feature", meaning: "fitur" },
    { word: "liberal", meaning: "liberal" },
    { word: "consult", meaning: "berkonsultasi" },
    { word: "ideology", meaning: "ideologi" },
    { word: "require", meaning: "membutuhkan" },
    { word: "duration", meaning: "durasi" },
    { word: "site", meaning: "situs" },
    { word: "institute", meaning: "lembaga" },
    { word: "pursue", meaning: "mengejar" },
    { word: "structure", meaning: "struktur" },
    { word: "convert", meaning: "mengubah" },
    { word: "crucial", meaning: "krusial" },
    { word: "initial", meaning: "awal" },
    { word: "inevitable", meaning: "tak terhindarkan" },
    { word: "prior", meaning: "sebelumnya" },
    { word: "psychology", meaning: "psikologi" },
    { word: "attempt", meaning: "upaya" },
    { word: "persist", meaning: "bertahan" },
    { word: "journal", meaning: "jurnal" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "indicate", meaning: "menunjukkan" },
    { word: "simulate", meaning: "mensimulasikan" },
    { word: "protocol", meaning: "protokol" },
    { word: "priority", meaning: "prioritas" },
    { word: "focus", meaning: "fokus" },
    { word: "prefer", meaning: "lebih suka" },
    { word: "occur", meaning: "terjadi" },
    { word: "foundation", meaning: "fondasi" },
    { word: "reveal", meaning: "mengungkapkan" },
    { word: "output", meaning: "output" },
    { word: "mediate", meaning: "menengahi" },
    { word: "option", meaning: "opsi" },
    { word: "recommend", meaning: "merekomendasikan" },
    { word: "supplement", meaning: "suplemen" },
    { word: "assist", meaning: "membantu" },
    { word: "evaluate", meaning: "mengevaluasi" },
    { word: "link", meaning: "menghubungkan" },
    { word: "publish", meaning: "menerbitkan" },
    { word: "render", meaning: "memberikan" },
    { word: "somewhat", meaning: "agak" },
    { word: "paradigm", meaning: "paradigma" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "explore", meaning: "menjelajahi" },
    { word: "positive", meaning: "positif" },
    { word: "diminish", meaning: "mengurangi" },
    { word: "flexible", meaning: "fleksibel" },
    { word: "internal", meaning: "internal" },
    { word: "predict", meaning: "memprediksi" },
    { word: "arbitrary", meaning: "sewenang-wenang" },
    { word: "topic", meaning: "topik" },
    { word: "issue", meaning: "masalah" },
    { word: "solve", meaning: "memecahkan" },
    { word: "supplement", meaning: "suplemen" },
    { word: "reveal", meaning: "mengungkapkan" },
    { word: "modify", meaning: "memodifikasi" },
    { word: "priority", meaning: "prioritas" },
    { word: "paragraph", meaning: "paragraf" },
    { word: "assure", meaning: "memastikan" },
    { word: "promote", meaning: "mempromosikan" },
    { word: "percent", meaning: "persen" },
    { word: "acquire", meaning: "memperoleh" },
    { word: "minimum", meaning: "minimum" },
    { word: "allocate", meaning: "mengalokasikan" },
    { word: "integral", meaning: "integral" },
    { word: "conclude", meaning: "menyimpulkan" },
    { word: "entity", meaning: "entitas" },
    { word: "inform", meaning: "memberi tahu" },
    { word: "zone", meaning: "zona" },
    { word: "integral", meaning: "integral" },
    { word: "implicit", meaning: "tersirat" },
    { word: "attempt", meaning: "upaya" },
    { word: "withdraw", meaning: "menarik diri" },
    { word: "topic", meaning: "topik" },
    { word: "ideology", meaning: "ideologi" },
    { word: "theme", meaning: "tema" },
    { word: "require", meaning: "membutuhkan" },
    { word: "qualitative", meaning: "kualitatif" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "scenario", meaning: "skenario" },
    { word: "yield", meaning: "menghasilkan" },
    { word: "transmit", meaning: "mengirimkan" },
    { word: "paradigm", meaning: "paradigma" },
    { word: "fund", meaning: "dana" },
    { word: "correspond", meaning: "sesuai" },
    { word: "prime", meaning: "utama" },
    { word: "zone", meaning: "zona" },
    { word: "attempt", meaning: "upaya" },
    { word: "minimum", meaning: "minimum" },
    { word: "psychology", meaning: "psikologi" },
    { word: "remove", meaning: "menghapus" },
    { word: "yield", meaning: "menghasilkan" },
    { word: "duration", meaning: "durasi" },
    { word: "participate", meaning: "berpartisipasi" },
    { word: "somewhat", meaning: "agak" },
    { word: "maintain", meaning: "memelihara" },
    { word: "transfer", meaning: "mentransfer" },
    { word: "topic", meaning: "topik" },
    { word: "scenario", meaning: "skenario" },
    { word: "indicate", meaning: "menunjukkan" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "positive", meaning: "positif" },
    { word: "evaluate", meaning: "mengevaluasi" },
    { word: "complex", meaning: "kompleks" },
    { word: "project", meaning: "proyek" },
    { word: "expert", meaning: "ahli" },
    { word: "portion", meaning: "bagian" },
    { word: "enhance", meaning: "meningkatkan" },
    { word: "encourage", meaning: "mendorong" },
    { word: "perspective", meaning: "perspektif" },
    { word: "whereas", meaning: "sedangkan" },
    { word: "allocate", meaning: "mengalokasikan" },
    { word: "evolve", meaning: "berevolusi" },
    { word: "initiate", meaning: "memulai" },
    { word: "impose", meaning: "memaksakan" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "revolution", meaning: "revolusi" },
    { word: "site", meaning: "situs" },
    { word: "render", meaning: "memberikan" },
    { word: "recover", meaning: "memulihkan" },
    { word: "constrain", meaning: "membatasi" },
    { word: "transmit", meaning: "mengirimkan" },
    { word: "scenario", meaning: "skenario" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "mention", meaning: "menyebutkan" },
    { word: "predominant", meaning: "dominan" },
    { word: "insert", meaning: "memasukkan" },
    { word: "phase", meaning: "fase" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "evolve", meaning: "berevolusi" },
    { word: "supplement", meaning: "suplemen" },
    { word: "terminate", meaning: "mengakhiri" },
    { word: "output", meaning: "output" },
    { word: "monitor", meaning: "memantau" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "assemble", meaning: "merakit" },
    { word: "evolve", meaning: "berevolusi" },
    { word: "focus", meaning: "fokus" },
    { word: "framework", meaning: "kerangka kerja" },
    { word: "transfer", meaning: "mentransfer" },
    { word: "status", meaning: "status" },
    { word: "style", meaning: "gaya" },
    { word: "require", meaning: "membutuhkan" },
    { word: "plus", meaning: "plus" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "vary", meaning: "bervariasi" },
    { word: "compare", meaning: "membandingkan" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "concentrate", meaning: "berkonsentrasi" },
    { word: "foundation", meaning: "fondasi" },
    { word: "paradigm", meaning: "paradigma" },
    { word: "transform", meaning: "mengubah" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "conceive", meaning: "membayangkan" },
    { word: "persist", meaning: "bertahan" },
    { word: "perspective", meaning: "perspektif" },
    { word: "crucial", meaning: "krusial" },
    { word: "compile", meaning: "mengkompilasi" },
    { word: "outcome", meaning: "hasil" },
    { word: "topic", meaning: "topik" },
    { word: "purchase", meaning: "membeli" },
    { word: "restrict", meaning: "membatasi" },
    { word: "transform", meaning: "mengubah" },
    { word: "protocol", meaning: "protokol" },
    { word: "explore", meaning: "menjelajahi" },
    { word: "series", meaning: "seri" },
    { word: "strategy", meaning: "strategi" },
    { word: "statistic", meaning: "statistik" },
    { word: "author", meaning: "penulis" },
    { word: "specify", meaning: "menentukan" },
    { word: "output", meaning: "output" },
    { word: "prime", meaning: "utama" },
    { word: "describe", meaning: "menggambarkan" },
    { word: "stress", meaning: "tekanan" },
    { word: "detect", meaning: "mendeteksi" },
    { word: "foundation", meaning: "fondasi" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "precede", meaning: "mendahului" },
    { word: "describe", meaning: "menggambarkan" },
    { word: "definite", meaning: "pasti" },
    { word: "invest", meaning: "berinvestasi" },
    { word: "persist", meaning: "bertahan" },
    { word: "sequence", meaning: "urutan" },
    { word: "rigid", meaning: "kaku" },
    { word: "persist", meaning: "bertahan" },
    { word: "ongoing", meaning: "berlangsung" },
    { word: "issue", meaning: "masalah" },
    { word: "convince", meaning: "meyakinkan" },
    { word: "zone", meaning: "zona" },
    { word: "output", meaning: "output" },
    { word: "inspect", meaning: "memeriksa" },
    { word: "append", meaning: "melampirkan" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "modify", meaning: "memodifikasi" },
    { word: "undertake", meaning: "melakukan" },
    { word: "valid", meaning: "valid" },
    { word: "prior", meaning: "sebelumnya" },
    { word: "supplement", meaning: "suplemen" },
    { word: "section", meaning: "bagian" },
    { word: "automate", meaning: "mengotomatiskan" },
    { word: "quote", meaning: "mengutip" },
    { word: "publication", meaning: "publikasi" },
    { word: "mediate", meaning: "menengahi" },
    { word: "withdraw", meaning: "menarik diri" },
    { word: "nevertheless", meaning: "namun demikian" },
    { word: "equivalent", meaning: "setara" },
    { word: "period", meaning: "periode" },
    { word: "automate", meaning: "mengotomatiskan" },
    { word: "uniform", meaning: "seragam" },
    { word: "subsequent", meaning: "berikutnya" },
    { word: "ensure", meaning: "memastikan" },
    { word: "justify", meaning: "membenarkan" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "recommend", meaning: "merekomendasikan" },
    { word: "orient", meaning: "mengorientasikan" },
    { word: "renew", meaning: "memperbarui" },
    { word: "persist", meaning: "bertahan" },
    { word: "inhibit", meaning: "menghambat" },
    { word: "percent", meaning: "persen" },
    { word: "identify", meaning: "mengidentifikasi" },
    { word: "justify", meaning: "membenarkan" },
    { word: "plus", meaning: "plus" },
    { word: "coherent", meaning: "koheren" },
    { word: "consult", meaning: "berkonsultasi" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "emerge", meaning: "muncul" },
    { word: "yield", meaning: "menghasilkan" },
    { word: "inspect", meaning: "memeriksa" },
    { word: "convert", meaning: "mengubah" },
    { word: "policy", meaning: "kebijakan" },
    { word: "fundamental", meaning: "fundamental" },
    { word: "undertake", meaning: "melakukan" },
    { word: "liberal", meaning: "liberal" },
    { word: "suggest", meaning: "menyarankan" },
    { word: "ongoing", meaning: "berlangsung" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "improve", meaning: "memperbaiki" },
    { word: "debate", meaning: "debat" },
    { word: "issue", meaning: "masalah" },
    { word: "currency", meaning: "mata uang" },
    { word: "currency", meaning: "mata uang" },
    { word: "suggest", meaning: "menyarankan" },
    { word: "internal", meaning: "internal" },
    { word: "predominant", meaning: "dominan" },
    { word: "suggest", meaning: "menyarankan" },
    { word: "topic", meaning: "topik" },
    { word: "ideology", meaning: "ideologi" },
    { word: "indicate", meaning: "menunjukkan" },
    { word: "psychology", meaning: "psikologi" },
    { word: "neutral", meaning: "netral" },
    { word: "assist", meaning: "membantu" },
    { word: "attempt", meaning: "upaya" },
    { word: "assure", meaning: "memastikan" },
    { word: "expert", meaning: "ahli" },
    { word: "absorb", meaning: "menyerap" },
    { word: "external", meaning: "eksternal" },
    { word: "primary", meaning: "utama" },
    { word: "compare", meaning: "membandingkan" },
    { word: "minimize", meaning: "meminimalkan" },
    { word: "strategy", meaning: "strategi" },
    { word: "relax", meaning: "bersantai" },
    { word: "journal", meaning: "jurnal" },
    { word: "relax", meaning: "bersantai" },
    { word: "margin", meaning: "margin" },
    { word: "perspective", meaning: "perspektif" },
    { word: "significant", meaning: "signifikan" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "liberal", meaning: "liberal" },
    { word: "grant", meaning: "memberikan" },
    { word: "percent", meaning: "persen" },
    { word: "internal", meaning: "internal" },
    { word: "legislate", meaning: "membuat undang-undang" },
    { word: "efficient", meaning: "efisien" },
    { word: "promote", meaning: "mempromosikan" },
    { word: "produce", meaning: "menghasilkan" },
    { word: "draft", meaning: "draf" },
    { word: "reveal", meaning: "mengungkapkan" },
    { word: "release", meaning: "melepaskan" },
    { word: "ensure", meaning: "memastikan" },
    { word: "voluntary", meaning: "sukarela" },
    { word: "retain", meaning: "mempertahankan" },
    { word: "assure", meaning: "memastikan" },
    { word: "uniform", meaning: "seragam" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "attempt", meaning: "upaya" },
    { word: "project", meaning: "proyek" },
    { word: "item", meaning: "item" },
    { word: "phase", meaning: "fase" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "display", meaning: "menampilkan" },
    { word: "margin", meaning: "margin" },
    { word: "initiate", meaning: "memulai" },
    { word: "principal", meaning: "utama" },
    { word: "display", meaning: "menampilkan" },
    { word: "issue", meaning: "masalah" },
    { word: "technique", meaning: "teknik" },
    { word: "reflect", meaning: "mencerminkan" },
    { word: "radical", meaning: "radikal" },
    { word: "draft", meaning: "draf" },
    { word: "approach", meaning: "pendekatan" },
    { word: "persist", meaning: "bertahan" },
    { word: "append", meaning: "melampirkan" },
    { word: "perceive", meaning: "mempersepsikan" },
    { word: "seek", meaning: "mencari" },
    { word: "create", meaning: "membuat" },
    { word: "reinforce", meaning: "memperkuat" },
    { word: "transport", meaning: "mengangkut" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "secure", meaning: "mengamankan" },
    { word: "mature", meaning: "dewasa" },
    { word: "differentiate", meaning: "membedakan" },
    { word: "intrinsic", meaning: "intrinsik" },
    { word: "conform", meaning: "menyesuaikan diri" },
    { word: "eliminate", meaning: "menghilangkan" },
    { word: "transform", meaning: "mengubah" },
    { word: "margin", meaning: "margin" },
    { word: "balance", meaning: "keseimbangan" },
    { word: "resource", meaning: "sumber daya" },
    { word: "enable", meaning: "memungkinkan" },
    { word: "ministry", meaning: "kementerian" },
    { word: "structure", meaning: "struktur" },
    { word: "status", meaning: "status" },
    { word: "offset", meaning: "mengimbangi" },
    { word: "convert", meaning: "mengubah" },
    { word: "orient", meaning: "mengorientasikan" },
    { word: "assure", meaning: "memastikan" },
    { word: "similar", meaning: "serupa" },
    { word: "implicate", meaning: "melibatkan" },
    { word: "highlight", meaning: "menyoroti" },
    { word: "paradigm", meaning: "paradigma" },
    { word: "grade", meaning: "nilai" },
    { word: "motivate", meaning: "memotivasi" },
    { word: "issue", meaning: "masalah" },
    { word: "conceive", meaning: "membayangkan" },
    { word: "temporary", meaning: "sementara" },
    { word: "rely", meaning: "mengandalkan" },
    { word: "interpret", meaning: "menafsirkan" },
    { word: "correspond", meaning: "sesuai" },
    { word: "priority", meaning: "prioritas" },
    { word: "transform", meaning: "mengubah" },
    { word: "rely", meaning: "mengandalkan" },
    { word: "dominate", meaning: "mendominasi" },
    { word: "forthcoming", meaning: "mendatang" },
    { word: "threaten", meaning: "mengancam" },
    { word: "recommend", meaning: "merekomendasikan" },
    { word: "crucial", meaning: "krusial" },
    { word: "intense", meaning: "intens" },
    { word: "supplement", meaning: "suplemen" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "integral", meaning: "integral" },
    { word: "abstract", meaning: "abstrak" },
    { word: "describe", meaning: "menggambarkan" },
    { word: "differentiate", meaning: "membedakan" },
    { word: "mutual", meaning: "timbal balik" },
    { word: "crucial", meaning: "krusial" },
    { word: "require", meaning: "membutuhkan" },
    { word: "invest", meaning: "berinvestasi" },
    { word: "isolate", meaning: "mengisolasi" },
    { word: "transform", meaning: "mengubah" },
    { word: "issue", meaning: "masalah" },
    { word: "initiate", meaning: "memulai" },
    { word: "sustain", meaning: "mempertahankan" },
    { word: "illustrate", meaning: "mengilustrasikan" },
    { word: "influence", meaning: "mempengaruhi" },
    { word: "restore", meaning: "memulihkan" },
    { word: "transfer", meaning: "mentransfer" },
    { word: "accurate", meaning: "akurat" },
    { word: "voluntary", meaning: "sukarela" },
    { word: "restrict", meaning: "membatasi" },
    { word: "cease", meaning: "berhenti" },
    { word: "sum", meaning: "jumlah" },
    { word: "undertake", meaning: "melakukan" },
    { word: "recommend", meaning: "merekomendasikan" },
    { word: "convert", meaning: "mengubah" },
    { word: "fundamental", meaning: "fundamental" },
    { word: "somewhat", meaning: "agak" },
    { word: "initial", meaning: "awal" },
    { word: "likewise", meaning: "demikian juga" },
    { word: "conclude", meaning: "menyimpulkan" },
    { word: "explicit", meaning: "eksplisit" },
    { word: "structure", meaning: "struktur" },
    { word: "supplement", meaning: "suplemen" },
    { word: "yield", meaning: "menghasilkan" },
    { word: "highlight", meaning: "menyoroti" },
    { word: "topic", meaning: "topik" },
    { word: "establish", meaning: "membangun" },
    { word: "survive", meaning: "bertahan hidup" },
    { word: "instance", meaning: "contoh" },
    { word: "proceed", meaning: "melanjutkan" },
    { word: "conceive", meaning: "membayangkan" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "suggest", meaning: "menyarankan" },
    { word: "rely", meaning: "mengandalkan" },
    { word: "predict", meaning: "memprediksi" },
    { word: "constrain", meaning: "membatasi" },
    { word: "consult", meaning: "berkonsultasi" },
    { word: "strategy", meaning: "strategi" },
    { word: "unique", meaning: "unik" },
    { word: "link", meaning: "menghubungkan" },
    { word: "summary", meaning: "ringkasan" },
    { word: "conclude", meaning: "menyimpulkan" },
    { word: "acquire", meaning: "memperoleh" },
    { word: "strategy", meaning: "strategi" },
    { word: "mutual", meaning: "timbal balik" },
    { word: "parameter", meaning: "parameter" },
    { word: "evident", meaning: "jelas" },
    { word: "assure", meaning: "memastikan" },
    { word: "substitute", meaning: "menggantikan" },
    { word: "so-called", meaning: "yang disebut" },
    { word: "isolate", meaning: "mengisolasi" },
    { word: "perceive", meaning: "mempersepsikan" },
    { word: "allocate", meaning: "mengalokasikan" },
    { word: "sufficient", meaning: "cukup" },
    { word: "incorporate", meaning: "menggabungkan" },
    { word: "crucial", meaning: "krusial" },
    { word: "regulate", meaning: "mengatur" },
    { word: "yield", meaning: "menghasilkan" },
    { word: "automate", meaning: "mengotomatiskan" },
    { word: "foundation", meaning: "fondasi" },
    { word: "evaluate", meaning: "mengevaluasi" },
    { word: "highlight", meaning: "menyoroti" },
    { word: "recover", meaning: "memulihkan" },
    { word: "percent", meaning: "persen" },
    { word: "participate", meaning: "berpartisipasi" },
    { word: "fundamental", meaning: "fundamental" },
    { word: "consult", meaning: "berkonsultasi" },
    { word: "significant", meaning: "signifikan" },
    { word: "coordinate", meaning: "mengkoordinasikan" },
    { word: "section", meaning: "bagian" },
    { word: "role", meaning: "peran" },
    { word: "prior", meaning: "sebelumnya" },
    { word: "transform", meaning: "mengubah" },
    { word: "temporary", meaning: "sementara" },
    { word: "phase", meaning: "fase" },
    { word: "convince", meaning: "meyakinkan" },
    { word: "transfer", meaning: "mentransfer" },
    { word: "topic", meaning: "topik" },
    { word: "institute", meaning: "lembaga" },
    { word: "react", meaning: "bereaksi" },
    { word: "investigate", meaning: "menyelidiki" },
    { word: "occur", meaning: "terjadi" },
    { word: "attribute", meaning: "ciri" },
    { word: "theme", meaning: "tema" },
    { word: "pose", meaning: "menimbulkan" },
    { word: "interval", meaning: "interval" },
    { word: "mention", meaning: "menyebutkan" },
    { word: "assist", meaning: "membantu" },
    { word: "fundamental", meaning: "fundamental" },
    { word: "proportion", meaning: "proporsi" },
    { word: "principal", meaning: "utama" },
    { word: "approach", meaning: "pendekatan" },
    { word: "federal", meaning: "federal" },
    { word: "strategy", meaning: "strategi" },
    { word: "incentive", meaning: "insentif" },
    { word: "abandon", meaning: "meninggalkan" },
    { word: "brief", meaning: "singkat" },
    { word: "project", meaning: "proyek" },
    { word: "participate", meaning: "berpartisipasi" },
    { word: "combine", meaning: "menggabungkan" },
    { word: "liberal", meaning: "liberal" },
    { word: "pursue", meaning: "mengejar" },
    { word: "institute", meaning: "lembaga" },
    { word: "integral", meaning: "integral" },
    { word: "apparent", meaning: "jelas" },
    { word: "assemble", meaning: "merakit" },
    { word: "solve", meaning: "memecahkan" },
    { word: "minimum", meaning: "minimum" },
    { word: "expert", meaning: "ahli" },
    { word: "process", meaning: "proses" },
    { word: "concurrent", meaning: "bersamaan" },
    { word: "combine", meaning: "menggabungkan" },
    { word: "rational", meaning: "rasional" },
    { word: "approach", meaning: "pendekatan" },
    { word: "insight", meaning: "wawasan" },
    { word: "justify", meaning: "membenarkan" },
    { word: "item", meaning: "item" },
    { word: "scenario", meaning: "skenario" },
    { word: "phenomenon", meaning: "fenomena" },
    { word: "regulate", meaning: "mengatur" },
    { word: "contradict", meaning: "bertentangan" }
];